sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # Used in deploy.sh
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  # The following 3 commands and creation of k8s Secret
  # should be run in Google Cloud console as well.
  # Check server-deployment.yaml
  # In case of success secret should be visible in GC under
  # Kubernetes Engine -> Configuration
  - gcloud config set project multi-k8s-264310
  - gcloud config set compute/zone europe-north1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Tests are run on dev version only
  - docker build -t beaglefoot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true beaglefoot/react-test npm run test

deploy:
  # No built-in provider for k8s. Have to build from scratch.
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
