apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: beaglefoot.me
  dnsNames:
    - beaglefoot.me
    - www.beaglefoot.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - beaglefoot.me
          - www.beaglefoot.me
